[pytest]

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    tc1: Login with predefined users
    tc2: Login with invalid credentials
    tc3: Logout functionality
    tc4: Cart icon visibility
    tc5: Random product selection
    tc6: Add products to cart
    tc7: Validate cart products
    tc8: Checkout and order validation
    tc9: Product sorting
    tc10: Reset application state
    login: Login related tests
    cart: Cart related tests
    checkout: Checkout related tests

addopts = -v --html=reports/report.html --self-contained-html

log_cli = true